99cats_auth/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cats, except: :destroy
  resources :cat_rental_requests, only: [:new, :create] do
    post 'approve', on: :member
    post 'deny', on: :member
  end
  resources :users, only: [:new, :create]
  resource :session, only: [:new, :create, :destroy]

  root to: redirect('/cats')
end

99cats_auth/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NinetyNineCats</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if flash[:errors] %>
      <h3>errors: </h3>
       <ul>
         <% flash[:errors].each do |error| %>
         <li> <%= error %> </li>
         <% end %>
       </ul>
    <% end %>
    <% if self.current_user %>
      <h1>Hello <%= self.current_user.username %>!</h1>
      <form class="" action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token  %>">
        <input type="hidden" name="_method" value="DELETE">
        <input type="submit" value="Log Out">
      </form>
      <% else %>
      <form class="" action="<%= new_session_url %>" method="get">

        <input type="submit" value="Log In">
      </form>
      <form class="" action="<%= new_user_url %>" method="get">

        <input type="submit" value="Sign Up">
      </form>
    <% end %>
    <%= yield %>
  </body>
</html>